## Numpy, Pandas & Matplotlib 

In [43]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import pyreadr


Numpy

In [16]:
# crear un array numpy a partir de una lista
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [17]:
# Crear un array numpy de ceros
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# Crear un array numpy de unos
ones_arr = np.ones((2, 4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# Crear un array numpy con un rango de valores
range_arr = np.arange(0, 10, 2)  # De 0 a 10 con paso de 2, exclusivo
print(range_arr)


[0 2 4 6 8]


In [20]:
# Crear un array numpy con valores igualmente espaciados
linspace_arr = np.linspace(0, 1, 5)  # De 0 a 1 con 5 valores, no exclusivo
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [21]:
# Crear un array numpy
arr = np.array([10, 20, 30, 40, 50])

# Indexación
print(arr[1])  # Elemento en el índice 1

# Slicing
print(arr[1:4])  # Subarray del índice 1 al 3


20
[20 30 40]


In [26]:
# Crear un array numpy
arr = np.array([1, 2, 3, 4, 5])

# Calcular la media
mean_val = np.mean(arr)
print(mean_val)

# Calcular la suma
sum_val = np.sum(arr)
print(sum_val)

# Calcular la desviación estándar
std_val = np.std(arr)
print(std_val)


3.0
15
1.4142135623730951


In [25]:
# Crear un array numpy 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [27]:
# Cambiar la forma de un array
reshaped_arr = arr_2d.reshape((3, 2))
print(reshaped_arr)


[[1 2]
 [3 4]
 [5 6]]


In [28]:
# Transponer un array
transposed_arr = arr_2d.transpose()
print(transposed_arr)


[[1 4]
 [2 5]
 [3 6]]


In [30]:
# Crear dos matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Multiplicar matrices
result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)


[[19 22]
 [43 50]]


In [31]:
# Inversa de una matriz
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
# Determinante de una matriz
det_matrix = np.linalg.det(matrix)
print(det_matrix)


-2.0000000000000004


Estructuras de Datos Principales en Pandas: Series y DataFrame

In [33]:
# Crear una serie
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [34]:
# Crear un DataFrame
data = {'Nombre': ['Alice', 'Bob', 'Charlie'],
        'Edad': [25, 30, 35],
        'Ciudad': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
print(df)


    Nombre  Edad       Ciudad
0    Alice    25     New York
1      Bob    30  Los Angeles
2  Charlie    35      Chicago


In [36]:
# Crear una serie desde un diccionario
data = {'a': 1, 'b': 2, 'c': 3}
series = pd.Series(data)
print(series)


a    1
b    2
c    3
dtype: int64


In [44]:
# Leer datos desde un archivo CSV
df = pd.read_csv('../data/raw/Airbnb_NY.csv')
print(df)


             id                                               name   host_id  \
0          2539                 Clean & quiet apt home by the park      2787   
1          2595                              Skylit Midtown Castle      2845   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632   
3          3831                    Cozy Entire Floor of Brownstone      4869   
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192   
...         ...                                                ...       ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441   
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630   
48892  36485431            Sunny Studio at Historical Neighborhood  23492952   
48893  36485609               43rd St. Time Square-cozy single bed  30985759   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814   

           host_name neighbourhood_grou

In [52]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [ ]:
# Leer datos desde un archivo Excel
df = pd.read_excel('datos.xlsx', sheet_name='Sheet1')
print(df)


In [46]:
# Seleccionar una columna
print(df['name'])


0                       Clean & quiet apt home by the park
1                                    Skylit Midtown Castle
2                      THE VILLAGE OF HARLEM....NEW YORK !
3                          Cozy Entire Floor of Brownstone
4         Entire Apt: Spacious Studio/Loft by central park
                               ...                        
48890      Charming one bedroom - newly renovated rowhouse
48891        Affordable room in Bushwick/East Williamsburg
48892              Sunny Studio at Historical Neighborhood
48893                 43rd St. Time Square-cozy single bed
48894    Trendy duplex in the very heart of Hell's Kitchen
Name: name, Length: 48895, dtype: object


In [53]:
# Seleccionar múltiples columnas
print(df[['name', 'price']])

                                                    name  price
0                     Clean & quiet apt home by the park    149
1                                  Skylit Midtown Castle    225
2                    THE VILLAGE OF HARLEM....NEW YORK !    150
3                        Cozy Entire Floor of Brownstone     89
4       Entire Apt: Spacious Studio/Loft by central park     80
...                                                  ...    ...
48890    Charming one bedroom - newly renovated rowhouse     70
48891      Affordable room in Bushwick/East Williamsburg     40
48892            Sunny Studio at Historical Neighborhood    115
48893               43rd St. Time Square-cozy single bed     55
48894  Trendy duplex in the very heart of Hell's Kitchen     90

[48895 rows x 2 columns]


In [49]:
# Seleccionar una fila por índice
print(df.loc[0])


id                                                              2539
name                              Clean & quiet apt home by the park
host_id                                                         2787
host_name                                                       John
neighbourhood_group                                         Brooklyn
neighbourhood                                             Kensington
latitude                                                    40.64749
longitude                                                  -73.97237
room_type                                               Private room
price                                                            149
minimum_nights                                                     1
number_of_reviews                                                  9
last_review                                               2018-10-19
reviews_per_month                                               0.21
calculated_host_listings_count    

In [50]:
# Seleccionar múltiples filas por índice
print(df.loc[0:1])

     id                                name  host_id host_name  \
0  2539  Clean & quiet apt home by the park     2787      John   
1  2595               Skylit Midtown Castle     2845  Jennifer   

  neighbourhood_group neighbourhood  latitude  longitude        room_type  \
0            Brooklyn    Kensington  40.64749  -73.97237     Private room   
1           Manhattan       Midtown  40.75362  -73.98377  Entire home/apt   

   price  minimum_nights  number_of_reviews last_review  reviews_per_month  \
0    149               1                  9  2018-10-19               0.21   
1    225               1                 45  2019-05-21               0.38   

   calculated_host_listings_count  availability_365  
0                               6               365  
1                               2               355  


In [56]:
# Filtrar filas basadas en una condición
print(df[df['price'] > 0])


             id                                               name   host_id  \
0          2539                 Clean & quiet apt home by the park      2787   
1          2595                              Skylit Midtown Castle      2845   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632   
3          3831                    Cozy Entire Floor of Brownstone      4869   
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192   
...         ...                                                ...       ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441   
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630   
48892  36485431            Sunny Studio at Historical Neighborhood  23492952   
48893  36485609               43rd St. Time Square-cozy single bed  30985759   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814   

           host_name neighbourhood_grou

In [57]:
# Ordenar por una columna
df_sorted = df.sort_values(by='price')
print(df_sorted)


             id                                               name    host_id  \
26841  21291569  Coliving in Brooklyn! Modern design / Shared room  101970559   
25753  20608117                    Sunny, Quiet Room in Greenpoint    1641537   
26866  21304320             Best Coliving space ever! Shared room.  101970559   
25433  20333471      ★Hostel Style Room | Ideal Traveling Buddies★  131697576   
26259  20933849                              the best you can find   13709292   
...         ...                                                ...        ...   
6530    4737930                                 Spanish Harlem Apt    1235070   
40433  31340283  2br - The Heart of NYC: Manhattans Lower East ...    4382127   
17692  13894339    Luxury 1 bedroom apt. -stunning Manhattan views    5143901   
29238  22436899                                1-BR Lincoln Center   72390391   
9151    7003697                Furnished room in Astoria apartment   20582832   

      host_name neighbourho

In [75]:
# Identificar valores nulos
print(df.isnull().sum())


id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64


In [76]:
# Eliminar filas con valores nulos
df_filled = df.dropna()
print(df_cleaned)

             id                                              name    host_id  \
0          2539                Clean & quiet apt home by the park       2787   
1          2595                             Skylit Midtown Castle       2845   
3          3831                   Cozy Entire Floor of Brownstone       4869   
4          5022  Entire Apt: Spacious Studio/Loft by central park       7192   
5          5099         Large Cozy 1 BR Apartment In Midtown East       7322   
...         ...                                               ...        ...   
48782  36425863        Lovely Privet Bedroom with Privet Restroom   83554966   
48790  36427429                          No.2 with queen size bed  257683179   
48799  36438336                                   Seas The Moment  211644523   
48805  36442252                     1B-1B apartment near by Metro  273841667   
48852  36455809           Cozy Private Room in Bushwick, Brooklyn   74162901   

         host_name neighbourhood_group 

In [77]:
# Rellenar valores nulos
df_filled = df_filled.fillna(0)
print(df_filled)

             id                                              name    host_id  \
0          2539                Clean & quiet apt home by the park       2787   
1          2595                             Skylit Midtown Castle       2845   
3          3831                   Cozy Entire Floor of Brownstone       4869   
4          5022  Entire Apt: Spacious Studio/Loft by central park       7192   
5          5099         Large Cozy 1 BR Apartment In Midtown East       7322   
...         ...                                               ...        ...   
48782  36425863        Lovely Privet Bedroom with Privet Restroom   83554966   
48790  36427429                          No.2 with queen size bed  257683179   
48799  36438336                                   Seas The Moment  211644523   
48805  36442252                     1B-1B apartment near by Metro  273841667   
48852  36455809           Cozy Private Room in Bushwick, Brooklyn   74162901   

         host_name neighbourhood_group 

In [79]:
# Convertir columna a tipo de datos diferente
df['price'] = df['price'].astype(float)
print(df)


             id                                               name   host_id  \
0          2539                 Clean & quiet apt home by the park      2787   
1          2595                              Skylit Midtown Castle      2845   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632   
3          3831                    Cozy Entire Floor of Brownstone      4869   
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192   
...         ...                                                ...       ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441   
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630   
48892  36485431            Sunny Studio at Historical Neighborhood  23492952   
48893  36485609               43rd St. Time Square-cozy single bed  30985759   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814   

           host_name neighbourhood_grou

In [96]:
df_2 = pd.DataFrame(
    {'Animal': ['Falcon', 'Falcon','Parrot', 'Parrot'],
    'Max Speed': [380., 370., 24., 26.]}
    )

In [97]:
# Agrupar por una columna y calcular la media
grouped = df_2.groupby(['Animal']).mean()
print(grouped)


        Max Speed
Animal           
Falcon      375.0
Parrot       25.0


In [84]:
# Calcular la media de una columna
mean_price = df['price'].mean()
print(f'Media del precio: {mean_price}')

# Calcular la suma de una columna
sum_price = df['price'].sum()
print(f'Suma de los precios: {sum_price}')


Media del precio: 152.7206871868289
Suma de los precios: 7467278.0


In [100]:
# Descripción estadística del DataFrame
description = df_2.describe()
print(description)

        Max Speed
count    4.000000
mean   200.000000
std    202.115479
min     24.000000
25%     25.500000
50%    198.000000
75%    372.500000
max    380.000000
